input {
  beats {
    port => 5044
  }
}

filter {
  if [log][level] {
    mutate {
      lowercase => ["[log][level]"]
    }
  }

  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mobile-money-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
    manage_template => true
    template => "/usr/share/logstash/templates/mobile-money-logs-template.json"
    template_name => "mobile-money-logs"
    template_overwrite => true
  }
}
